'use client'

import Link from 'next/link'
import { collection, doc, getDocs, updateDoc } from 'firebase/firestore'
import { onAuthStateChanged, signInWithEmailAndPassword, signOut, type User } from 'firebase/auth'
import { useEffect, useState } from 'react'
import { firebaseAuth, firestore } from '@/lib/firebase'

type Proposal = { id: string; label: string; category: string; command: string; description: string; warning: string; status: string; authorEmail?: string }

export default function AdminCommandsPage() {
  const [user, setUser] = useState<User | null>(null); const [proposals, setProposals] = useState<Proposal[]>([]); const [form, setForm] = useState({ email: '', password: '' }); const [message, setMessage] = useState('')
  const adminUid = 'dTxIE4YXaNSlwLS2Qdd2Q3ynBtH2'
  const load = async (current: User) => { if (current.uid !== adminUid) { setMessage(`Esta cuenta no es administradora. UID detectado: ${current.uid}`); return } if (!firestore) { setMessage('Firebase no está configurado en este entorno.'); return } const snapshot = await getDocs(collection(firestore, 'commandProposals')); setProposals(snapshot.docs.map(item => ({ id: item.id, ...item.data() } as Proposal)).filter(item => item.status === 'pending')) }
  useEffect(() => { if (!firebaseAuth) { setMessage('Firebase no está configurado en este entorno.'); return () => undefined }; let unsubscribe: (() => void) | undefined; void signOut(firebaseAuth).then(() => { unsubscribe = onAuthStateChanged(firebaseAuth, current => { setUser(current); if (current) load(current).catch(() => setMessage('No se pudieron cargar las propuestas.')) }) }); return () => unsubscribe?.() }, [])
  const login = async (event: React.FormEvent) => { event.preventDefault(); setMessage(''); if (!firebaseAuth) { setMessage('Firebase no está configurado en este entorno.'); return }; try { await signInWithEmailAndPassword(firebaseAuth, form.email.trim(), form.password) } catch { setMessage('Inicio de sesión no válido. Usa el email y contraseña de la cuenta cuyo UID es el administrador configurado.') } }
  const review = async (proposal: Proposal, status: 'approved' | 'rejected') => { await updateDoc(doc(firestore, 'commandProposals', proposal.id), { status, reviewedAt: new Date().toISOString(), reviewedBy: user?.uid }); if (status === 'approved') await import('firebase/firestore').then(({ addDoc }) => addDoc(collection(firestore, 'commands'), { label: proposal.label, category: proposal.category, command: proposal.command, description: proposal.description, warning: proposal.warning, proposalId: proposal.id, approvedBy: user?.uid, createdAt: new Date().toISOString() })); if (user) await load(user) }
  return <main className="min-h-screen bg-slate-950 px-6 py-10 text-white"><div className="mx-auto max-w-5xl"><Link href="/" className="text-sm text-emerald-300">← LinuxKit</Link><h1 className="mt-8 text-4xl font-semibold">Revisión de comandos</h1><p className="mt-3 text-slate-400">Panel reservado para administradores. Inicia sesión con tu cuenta administrativa para continuar.</p>{message && <p role="alert" className="mt-4 rounded-xl border border-amber-900/60 bg-amber-950/30 p-4 text-sm text-amber-200">{message}</p>}{!user ? <form onSubmit={login} className="mt-8 grid max-w-md gap-4 rounded-2xl border border-slate-800 bg-slate-900 p-6"><input required type="email" placeholder="Email admin" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} className="rounded-lg bg-slate-950 p-3" /><input required type="password" placeholder="Contraseña" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} className="rounded-lg bg-slate-950 p-3" /><button className="rounded-lg bg-emerald-400 px-4 py-3 font-semibold text-slate-950">Entrar</button></form> : <div className="mt-8 grid gap-4">{proposals.length === 0 && <p className="rounded-xl border border-slate-800 p-5 text-slate-400">No hay propuestas pendientes.</p>}{proposals.map(proposal => <article key={proposal.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">{proposal.label}</h2><p className="text-sm text-emerald-300">{proposal.category} · {proposal.authorEmail}</p></div><span className="rounded-full bg-amber-950 px-3 py-1 text-xs text-amber-300">Pendiente</span></div><code className="mt-4 block overflow-x-auto rounded-lg bg-slate-950 p-4 text-sm text-emerald-300">{proposal.command}</code><p className="mt-3 text-sm text-slate-300">{proposal.description}</p><p className="mt-2 text-sm text-amber-300">Advertencia: {proposal.warning}</p><div className="mt-4 flex gap-3"><button onClick={() => review(proposal, 'approved')} className="rounded-lg bg-emerald-400 px-4 py-2 font-semibold text-slate-950">Aprobar</button><button onClick={() => review(proposal, 'rejected')} className="rounded-lg border border-red-400 px-4 py-2 text-red-300">Rechazar</button></div></article>)}</div>}{message && <p className="mt-4 text-amber-300">{message}</p>}</div></main>
}
