'use client'

import Link from 'next/link'
import { ArrowRight, Copy, ShieldCheck, Terminal } from 'lucide-react'
import { useState } from 'react'

const exercises = [
  { title: 'Detectar un escaneo', description: 'Busca patrones de reconocimiento en logs sin generar tráfico ofensivo.', command: "sudo grep -Ei 'Nmap|scan|SYN' /var/log/ suricata/eve.json 2>/dev/null | tail -50", note: 'Úsalo sobre logs de tu laboratorio.' },
  { title: 'Validar rate limiting', description: 'Comprueba la configuración existente y sus contadores desde el servidor.', command: 'sudo journalctl -u {{servicio}} --since "15 minutes ago" | grep -Ei "429|rate.?limit|thrott"', note: 'No genera solicitudes automáticamente.' },
  { title: 'Revisar reglas IDS/IPS', description: 'Lista reglas cargadas y verifica que el motor de detección esté activo.', command: 'sudo systemctl status {{servicio_ids}} --no-pager; sudo suricata --list-runmodes 2>/dev/null', note: 'Cambia servicio_ids por el servicio instalado.' },
  { title: 'Bloquear una IP de laboratorio', description: 'Aplica una regla de contención a una IP de prueba documentada.', command: 'sudo ufw deny from {{ip_laboratorio}} comment "laboratorio controlado"', note: 'Confirma la IP y ten una regla de reversión preparada.' },
  { title: 'Auditar intentos SSH', description: 'Resume autenticaciones fallidas y usuarios afectados.', command: "sudo journalctl -u ssh --since '{{periodo}}' | grep -Ei 'failed|invalid user' | tail -100", note: 'Solo análisis defensivo de registros.' },
  { title: 'Simular respuesta con archivo', description: 'Genera un evento local inocuo para validar alertas y documentación.', command: 'logger -t linuxkit-lab "evento de prueba autorizado"', note: 'No accede a otros sistemas ni explota servicios.' },
  { title: 'Detectar patrón de fuerza bruta', description: 'Analiza intentos fallidos ya registrados y resume IPs y usuarios afectados, sin generar autenticaciones.', command: "sudo journalctl -u ssh --since '{{periodo}}' | grep -Ei 'failed|invalid user' | awk '{print $NF}' | sort | uniq -c | sort -nr | head -20", note: 'Ejercicio defensivo: solo procesa logs existentes.' },
  { title: 'Comprobar Fail2ban', description: 'Verifica si Fail2ban está activo, qué jails carga y qué IPs están bloqueadas.', command: 'sudo fail2ban-client ping; sudo fail2ban-client status; sudo fail2ban-client status {{jail}}', note: 'No añade reglas ni bloquea direcciones automáticamente.' },
  { title: 'Revisar política de bloqueo', description: 'Inspecciona la configuración efectiva de SSH para comprobar límites de intentos y tiempos.', command: "sudo sshd -T | grep -Ei 'maxauthtries|loginGraceTime|authenticationmethods|allowusers|denyusers'", note: 'Solo lectura; aplica cambios en una ventana controlada.' },
  { title: 'Auditar paquetes vulnerables', description: 'Busca actualizaciones de seguridad disponibles sin explotar vulnerabilidades.', command: 'apt list --upgradable 2>/dev/null | grep -Ei "security|openssl|openssh|kernel"', note: 'Revisa el changelog y prueba actualizaciones antes de producción.' },
  { title: 'Validar exposición de servicios', description: 'Compara puertos escuchando con el inventario esperado y marca desviaciones.', command: 'sudo ss -tulpn; printf "\\nInventario esperado: {{puertos_esperados}}\\n"', note: 'No escanea terceros; compara el estado local documentado.' },
  { title: 'Simular alerta IDS local', description: 'Escribe un evento de prueba en el log local para comprobar que una regla de detección lo captura.', command: 'logger -p auth.warning -t linuxkit-lab "LAB_TEST suspicious-login source={{ip_laboratorio}}"', note: 'Evento local inocuo; elimina o etiqueta los datos de prueba.' },
  { title: 'Verificar mitigación de aplicación', description: 'Comprueba cabeceras de seguridad y códigos de respuesta de una aplicación propia.', command: 'curl --max-time 5 -sSI {{url}} | grep -Ei "HTTP/|strict-transport|content-security|x-frame|x-content-type"', note: 'Una solicitud HEAD puntual, sin payload ni explotación.' },
  { title: 'Revisión posterior al parche', description: 'Confirma versión del kernel, reinicio pendiente y servicios activos tras una corrección.', command: 'uname -r; test -f /var/run/reboot-required && echo "Reinicio pendiente" || echo "Sin reinicio pendiente"; systemctl --failed', note: 'Ayuda a cerrar un ejercicio de vulnerabilidad y mitigación.' },
]

export default function AtaquesControladosPage() {
  const [copied, setCopied] = useState('')
  const copy = async (command: string) => { await navigator.clipboard?.writeText(command); setCopied(command); setTimeout(() => setCopied(''), 1200) }
  return <main className="min-h-screen bg-slate-950 text-white"><header className="border-b border-slate-800"><div className="mx-auto flex min-h-16 max-w-6xl flex-wrap items-center justify-between gap-4 px-5 py-3"><Link href="/" className="flex items-center gap-2 font-semibold"><Terminal className="size-5 text-emerald-400" /> Linux<span className="text-emerald-400">Kit</span></Link><nav className="flex flex-wrap items-center gap-4 text-xs text-slate-400"><Link href="/">Explorar</Link><Link href="/biblioteca">Biblioteca</Link><Link className="font-semibold text-amber-300" href="/ataques-controlados">Ataques controlados</Link><Link href="/casos">Casos de uso</Link><Link href="/laboratorio">Laboratorio</Link></nav></div></header><section className="mx-auto max-w-6xl px-5 py-12"><div className="flex items-center gap-3 text-amber-300"><ShieldCheck className="size-5" /><span className="text-xs font-bold uppercase tracking-[0.18em]">Zona de simulación defensiva</span></div><div className="mt-5 max-w-3xl"><h1 className="text-4xl font-semibold tracking-tight sm:text-5xl">Ataques controlados, respuestas seguras.</h1><p className="mt-4 leading-7 text-slate-400">Ejercicios para validar detección, registros, contención y respuesta dentro de un entorno propio. No ejecuta fuerza bruta ni explotación: solo analiza registros, verifica controles y genera eventos locales de prueba. No incluye evasión, spoofing, flooding, payloads, credenciales ni instrucciones para comprometer servicios.</p></div><div className="mt-8 rounded-2xl border border-amber-400/30 bg-amber-400/10 p-5 text-sm leading-6 text-amber-100">Antes de comenzar: confirma el alcance, usa objetivos de laboratorio, documenta cada cambio y prepara una reversión. Estas plantillas analizan o generan eventos locales inocuos; no lanzan ataques contra terceros.</div><div className="mt-10 grid gap-4 md:grid-cols-2">{exercises.map((exercise) => <article key={exercise.title} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-lg font-semibold">{exercise.title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{exercise.description}</p><div className="mt-4 flex items-start gap-3 rounded-xl bg-slate-950 p-4"><code className="min-w-0 flex-1 whitespace-pre-wrap break-words font-mono text-xs leading-6 text-emerald-300">{exercise.command}</code><button type="button" onClick={() => copy(exercise.command)} className="rounded-lg border border-slate-700 p-2 text-slate-300" aria-label={`Copiar ${exercise.title}`}><Copy className="size-4" /></button></div><p className="mt-3 text-xs text-slate-500">{copied === exercise.command ? 'Copiado' : exercise.note}</p></article>)}</div><Link href="/laboratorio" className="mt-10 inline-flex items-center gap-2 text-sm font-semibold text-emerald-300">Abrir laboratorio completo <ArrowRight className="size-4" /></Link></section></main>
}
