'use client'

import Link from 'next/link'
import { addDoc, collection, serverTimestamp } from 'firebase/firestore'
import { createUserWithEmailAndPassword, signInWithEmailAndPassword } from 'firebase/auth'
import { useState } from 'react'
import { firebaseAuth, firestore } from '@/lib/firebase'

export default function ProponerComandoPage() {
  const [form, setForm] = useState({ label: '', category: 'Sistema', command: '', description: '', warning: '', email: '', password: '' })
  const [message, setMessage] = useState('')
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setMessage(''); try { const credential = firebaseAuth.currentUser ?? (await signInWithEmailAndPassword(firebaseAuth, form.email, form.password)).user; await addDoc(collection(firestore, 'commandProposals'), { label: form.label.trim(), category: form.category, command: form.command.trim(), description: form.description.trim(), warning: form.warning.trim(), authorId: credential.uid, authorEmail: credential.email, status: 'pending', createdAt: serverTimestamp() }); setMessage('Propuesta enviada para revisión administrativa.'); setForm({ ...form, label: '', command: '', description: '', warning: '' }) } catch { try { const credential = await createUserWithEmailAndPassword(firebaseAuth, form.email, form.password); await addDoc(collection(firestore, 'commandProposals'), { label: form.label.trim(), category: form.category, command: form.command.trim(), description: form.description.trim(), warning: form.warning.trim(), authorId: credential.user.uid, authorEmail: credential.user.email, status: 'pending', createdAt: serverTimestamp() }); setMessage('Cuenta creada y propuesta enviada.'); } catch { setMessage('No se pudo enviar. Revisa tus credenciales o crea la cuenta en Firebase.') } } }
  return <main className="min-h-screen bg-slate-950 px-6 py-10 text-white"><div className="mx-auto max-w-3xl"><Link href="/laboratorio" className="text-sm text-emerald-300">← Volver al laboratorio</Link><h1 className="mt-8 text-4xl font-semibold">Proponer un comando</h1><p className="mt-3 text-slate-400">Las propuestas quedan pendientes hasta que un administrador las revise y apruebe.</p><form onSubmit={submit} className="mt-8 grid gap-4 rounded-2xl border border-slate-800 bg-slate-900 p-6"><input required placeholder="Nombre del comando" value={form.label} onChange={e => setForm({ ...form, label: e.target.value })} className="rounded-lg bg-slate-950 p-3" /><select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} className="rounded-lg bg-slate-950 p-3"><option>Sistema</option><option>Procesos</option><option>Archivos</option><option>Redes</option><option>Seguridad</option><option>Auditoría</option><option>Contenedores</option></select><textarea required placeholder="Comando o plantilla" value={form.command} onChange={e => setForm({ ...form, command: e.target.value })} className="min-h-24 rounded-lg bg-slate-950 p-3 font-mono text-emerald-300" /><textarea required placeholder="Descripción y uso educativo" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} className="min-h-20 rounded-lg bg-slate-950 p-3" /><textarea required placeholder="Advertencias y restricciones" value={form.warning} onChange={e => setForm({ ...form, warning: e.target.value })} className="min-h-20 rounded-lg bg-slate-950 p-3" /><div className="grid gap-4 sm:grid-cols-2"><input required type="email" placeholder="Email Firebase" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} className="rounded-lg bg-slate-950 p-3" /><input required type="password" placeholder="Contraseña" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} className="rounded-lg bg-slate-950 p-3" /></div><button className="rounded-lg bg-emerald-400 px-4 py-3 font-semibold text-slate-950">Enviar propuesta</button>{message && <p className="text-sm text-emerald-300">{message}</p>}</form></div></main>
}
