import Link from 'next/link'
import { ArrowRight, AlertTriangle, CheckCircle2, Gauge, Globe, HardDrive, LockKeyhole, Terminal, UserRound, Search, Skull, ShieldAlert, FileSearch, Activity, Network, Clock3 } from 'lucide-react'

const cases = [
  { title: 'Servidor bajo ataque', description: 'Recopila evidencia, revisa accesos, procesos, conexiones y logs antes de aislar.', icon: AlertTriangle, tone: 'border-red-200 bg-red-50', steps: ['Identificar host y hora', 'Revisar usuarios y accesos', 'Inspeccionar red y procesos', 'Preservar logs', 'Aislar una IP validada'] },
  { title: 'Endurecer SSH', description: 'Revisa la configuración efectiva y valida cambios sin perder el acceso remoto.', icon: LockKeyhole, tone: 'border-emerald-200 bg-emerald-50', steps: ['sshd -T', 'Revisar PermitRootLogin', 'Revisar autenticación por contraseña', 'Comprobar firewall', 'Validar una segunda sesión'] },
  { title: 'Auditoría web autorizada', description: 'Inventaría exposición HTTP y WordPress con herramientas orientadas a diagnóstico.', icon: Globe, tone: 'border-blue-200 bg-blue-50', steps: ['Descubrir puertos con Nmap', 'Detectar versiones', 'Comprobar cabeceras HTTP', 'Auditar WordPress con WPScan', 'Guardar resultados'] },
  { title: 'VPS lento', description: 'Separa CPU, memoria, disco, red y servicios para encontrar el cuello de botella.', icon: Gauge, tone: 'border-amber-200 bg-amber-50', steps: ['uptime y free', 'top y procesos', 'df y du', 'ss -s', 'logs del servicio'] },
  { title: 'Disco lleno', description: 'Localiza el consumo, identifica logs grandes y libera espacio con control.', icon: HardDrive, tone: 'border-violet-200 bg-violet-50', steps: ['df -hT', 'du por directorios', 'find por tamaño', 'Revisar logs rotados', 'Eliminar solo tras confirmar'] },
  { title: 'Servicio caído', description: 'Diagnostica systemd, configuración, puertos y últimos mensajes del servicio.', icon: CheckCircle2, tone: 'border-slate-200 bg-slate-50', steps: ['systemctl status', 'journalctl -u', 'Validar configuración', 'Comprobar puerto', 'Reiniciar con criterio'] },
  { title: 'Intruso dentro del sistema', description: 'Investiga una posible intrusión activa: usuarios, persistencia, archivos recientes, procesos y conexiones. Primero preserva evidencia; después contiene.', icon: Skull, tone: 'border-red-200 bg-red-50', steps: ['Registrar contexto y no apagar impulsivamente', 'Buscar usuarios y claves nuevas', 'Revisar archivos modificados recientemente', 'Inspeccionar procesos y conexiones', 'Detener solo un PID confirmado', 'Revisar cron, systemd y accesos SSH'] },
  { title: 'Auditoría de cuentas', description: 'Detecta cuentas locales inesperadas, privilegios sudo y claves SSH añadidas en un servidor propio.', icon: UserRound, tone: 'border-orange-200 bg-orange-50', steps: ['Listar usuarios humanos', 'Revisar UID 0', 'Inspeccionar grupos sudo', 'Localizar authorized_keys', 'Comparar con inventario'] },
  { title: 'Caza de persistencia', description: 'Busca mecanismos comunes de ejecución automática sin borrar evidencia ni modificar el sistema durante la primera pasada.', icon: Search, tone: 'border-violet-200 bg-violet-50', steps: ['Listar cron de usuarios y root', 'Revisar servicios habilitados', 'Buscar timers systemd', 'Revisar perfiles de shell', 'Comparar archivos de inicio'] },
  { title: 'Posible ransomware', description: 'Contiene una posible propagación, preserva evidencia y prioriza la continuidad y recuperación desde backups verificados.', icon: HardDrive, tone: 'border-red-200 bg-red-50', steps: ['Aislar segmentos afectados', 'Registrar procesos y conexiones', 'Buscar extensiones o cambios masivos', 'Proteger backups', 'No borrar evidencia', 'Escalar y documentar'] },
  { title: 'TLS o certificado vencido', description: 'Diagnostica certificados, fechas, cadena de confianza y diferencias entre proxy y servicio origen.', icon: Globe, tone: 'border-cyan-200 bg-cyan-50', steps: ['Consultar fecha de expiración', 'Validar cadena TLS', 'Comparar DNS y endpoint', 'Revisar renovación automática', 'Recargar servicio con validación'] },
  { title: 'DNS o HTTP no responde', description: 'Separa resolución DNS, conectividad, puerto, proxy, aplicación y código HTTP.', icon: Globe, tone: 'border-blue-200 bg-blue-50', steps: ['Resolver DNS', 'Comprobar ruta', 'Probar puerto', 'Consultar cabeceras', 'Revisar logs del servicio'] },
  { title: 'Backup y recuperación', description: 'Verifica que existan copias, que sean legibles y que el procedimiento de restauración esté documentado.', icon: HardDrive, tone: 'border-emerald-200 bg-emerald-50', steps: ['Listar copias disponibles', 'Comprobar integridad', 'Revisar fechas y retención', 'Probar restauración aislada', 'Registrar resultado'] },
  { title: 'Contenedor comprometido', description: 'Investiga un contenedor sospechoso, conserva logs y reduce exposición sin destruir la evidencia inicial.', icon: Terminal, tone: 'border-indigo-200 bg-indigo-50', steps: ['Listar contenedores e imágenes', 'Guardar logs', 'Revisar procesos y puertos', 'Inspeccionar montajes', 'Aislar y reemplazar desde imagen confiable'] },
  { title: 'Ataque activo en el servidor', description: 'Contiene un incidente en curso sin destruir evidencia y prioriza alcance, continuidad y escalación.', icon: ShieldAlert, tone: 'border-red-200 bg-red-50', steps: ['Registrar hora y contexto', 'Preservar procesos y conexiones', 'Identificar alcance', 'Aislar de forma controlada', 'Proteger credenciales y backups', 'Documentar y escalar'] },
  { title: 'Auditoría de archivos sensibles', description: 'Busca cambios recientes, permisos inseguros y archivos fuera del inventario esperado.', icon: FileSearch, tone: 'border-amber-200 bg-amber-50', steps: ['Definir rutas autorizadas', 'Listar cambios recientes', 'Comparar hashes', 'Revisar propietarios y permisos', 'Guardar resultados'] },
  { title: 'Proceso sospechoso', description: 'Investiga procesos inesperados, su origen, usuario, archivos abiertos y conexiones asociadas.', icon: Activity, tone: 'border-orange-200 bg-orange-50', steps: ['Listar procesos completos', 'Relacionar PID y usuario', 'Revisar ejecutable y cwd', 'Consultar archivos abiertos', 'Comparar con inventario', 'Contener solo con autorización'] },
  { title: 'Conexiones salientes anómalas', description: 'Detecta destinos, puertos y procesos que generan tráfico no esperado desde el servidor.', icon: Network, tone: 'border-sky-200 bg-sky-50', steps: ['Capturar estado actual', 'Relacionar sockets y procesos', 'Resolver destinos con cautela', 'Comparar allowlist', 'Bloquear de forma reversible'] },
  { title: 'Persistencia en el sistema', description: 'Revisa cron, timers, servicios, perfiles y claves autorizadas sin modificar el sistema durante la primera pasada.', icon: Clock3, tone: 'border-violet-200 bg-violet-50', steps: ['Revisar cron de usuarios', 'Listar timers systemd', 'Auditar servicios habilitados', 'Revisar perfiles de shell', 'Comparar claves SSH', 'Preservar evidencia'] },
]

export default function CasosPage() { return <main className="min-h-screen bg-[#f7f8fa] text-slate-900"><Header /><section className="border-b bg-white"><div className="mx-auto max-w-6xl px-5 py-14 lg:px-8"><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-600">Playbooks operativos</p><h1 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Trabaja por situación.</h1><p className="mt-4 max-w-2xl text-slate-500">Cada caso agrupa el orden recomendado, el propósito y un acceso directo al laboratorio guiado.</p></div></section><section className="mx-auto grid max-w-6xl gap-4 px-5 py-10 md:grid-cols-2 lg:grid-cols-3 lg:px-8">{cases.map(({ title, description, icon: Icon, tone, steps }) => <article key={title} className={`rounded-2xl border p-5 ${tone}`}><Icon className="size-6 text-slate-700" /><h2 className="mt-5 text-lg font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p><ol className="mt-5 flex flex-col gap-2">{steps.map((step, index) => <li key={step} className="flex gap-2 text-xs text-slate-600"><span className="font-bold text-slate-400">0{index + 1}</span>{step}</li>)}</ol><Link href={`/laboratorio?caso=${encodeURIComponent(title)}`} className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-emerald-700">Abrir flujo <ArrowRight className="size-4" /></Link></article>)}</section></main> }
function Header() { return <header className="border-b bg-white"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5 lg:px-8"><Link href="/" className="flex items-center gap-3 font-semibold"><span className="flex size-9 items-center justify-center rounded-xl bg-slate-950 text-white"><Terminal className="size-5" /></span>Linux<span className="text-emerald-600">Kit</span></Link><nav className="flex gap-5 text-sm text-slate-500"><Link href="/#explorar">Explorar</Link><Link href="/biblioteca">Biblioteca</Link><Link className="text-amber-700" href="/ataques-controlados">Ataques controlados</Link><Link className="text-emerald-700" href="/proponer-comando">Proponer comando</Link><Link className="font-semibold text-slate-950" href="/casos">Casos de uso</Link><Link href="/laboratorio">Laboratorio</Link><Link href="/seguridad">Seguridad</Link></nav></div></header> }
