'use client'

import Link from 'next/link'
import { ArrowRight, BookOpen, Search, Terminal } from 'lucide-react'
import { useState } from 'react'

const groups = [
  { title: 'Sistema y diagnóstico', commands: [['uptime', 'Carga y tiempo encendido'], ['free -h', 'Memoria RAM y swap'], ['df -hT', 'Espacio por sistema de archivos'], ['du -xhd1 / | sort -h', 'Directorios que más ocupan'], ['uname -a', 'Kernel y arquitectura'], ['ps aux', 'Procesos activos'], ['top', 'Monitorización en tiempo real'], ['vmstat 1 5', 'CPU, memoria e I/O']] },
  { title: 'Archivos y permisos', commands: [['ls -lah', 'Lista archivos y permisos'], ['find', 'Busca por nombre, fecha o tamaño'], ['grep -Rni', 'Busca texto en archivos'], ['stat', 'Metadatos y fechas'], ['tail -f', 'Sigue un log en vivo'], ['chmod', 'Modifica permisos'], ['chown', 'Cambia propietario y grupo'], ['tar', 'Comprime o inspecciona archivos']] },
  { title: 'Redes y servicios', commands: [['ss -tulpn', 'Puertos y procesos escuchando'], ['ip addr', 'Interfaces y direcciones'], ['ip route', 'Rutas del sistema'], ['curl -I', 'Prueba HTTP y cabeceras'], ['dig', 'Consulta DNS'], ['systemctl', 'Gestiona servicios systemd'], ['journalctl', 'Consulta logs del sistema'], ['crontab -l', 'Tareas programadas']] },
  { title: 'Seguridad y auditoría', commands: [['sshd -T', 'Configuración efectiva de SSH'], ['ufw status', 'Estado del firewall'], ['last -ai', 'Historial de accesos'], ['sudo -l', 'Privilegios sudo'], ['nmap', 'Inventario de puertos autorizado'], ['wpscan', 'Auditoría WordPress autorizada'], ['nikto', 'Revisión web autorizada'], ['tcpdump', 'Captura de tráfico']] },
  { title: 'Incidentes y forense', commands: [['getent passwd', 'Inventario de usuarios'], ['find -mtime', 'Archivos modificados recientemente'], ['lsof -i', 'Procesos y conexiones'], ['kill -TERM', 'Detención ordenada de un PID confirmado'], ['systemctl list-timers', 'Persistencia systemd'], ['ausearch', 'Eventos de auditd'], ['sha256sum', 'Integridad de evidencias'], ['journalctl > archivo', 'Exporta logs']] },
  { title: 'DevOps y contenedores', commands: [['apt / dnf', 'Gestión de paquetes'], ['docker ps -a', 'Contenedores y estados'], ['docker inspect', 'Redes y montajes'], ['docker diff', 'Cambios dentro del contenedor'], ['docker compose up -d', 'Levanta una aplicación'], ['git status', 'Cambios del repositorio'], ['git log', 'Historial de commits'], ['rsync', 'Backups y sincronización']] },
]

export default function BibliotecaPage() {
  const [query, setQuery] = useState('')
  const results = groups.filter(({ title, commands }) => `${title} ${commands.flat().join(' ')}`.toLowerCase().includes(query.toLowerCase()))
  return <main className="min-h-screen bg-[#f7f8fa] text-slate-900"><Header active="Biblioteca" /><section className="border-b bg-white"><div className="mx-auto max-w-6xl px-5 py-14 lg:px-8"><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-600">Biblioteca Linux</p><h1 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Encuentra el comando correcto.</h1><p className="mt-4 max-w-2xl text-slate-500">Una vista enfocada para aprender por áreas de trabajo, no por una lista interminable.</p><div className="mt-8 flex max-w-xl items-center gap-3 rounded-2xl border bg-slate-50 px-4 py-3"><Search className="size-5 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Busca categoría o comando" className="flex-1 bg-transparent text-sm outline-none" /></div></div></section><section className="mx-auto grid max-w-6xl gap-4 px-5 py-10 md:grid-cols-2 lg:px-8">{results.map(({ title, commands }) => <article key={title} className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-slate-950 text-emerald-300"><Terminal className="size-5" /></div><div><h2 className="font-semibold">{title}</h2><p className="text-xs text-slate-400">{commands.length} comandos esenciales</p></div></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{commands.map(([command, description]) => <div key={command} className="rounded-xl border border-slate-100 bg-slate-50 p-3"><code className="font-mono text-xs font-semibold text-slate-800">{command}</code><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></div>)}</div><div className="mt-5 flex flex-wrap gap-4"><Link href={`/?categoria=${encodeURIComponent(title)}`} className="inline-flex items-center gap-2 text-sm font-semibold text-slate-700">Explorar comandos <ArrowRight className="size-4" /></Link><Link href={`/laboratorio?categoria=${encodeURIComponent(title)}`} className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-700">Abrir laboratorio <ArrowRight className="size-4" /></Link></div></article>)}</section></main>
}

function Header({ active }: { active: string }) { return <header className="border-b bg-white"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5 lg:px-8"><Link href="/" className="flex items-center gap-3 font-semibold"><span className="flex size-9 items-center justify-center rounded-xl bg-slate-950 text-white"><Terminal className="size-5" /></span>Linux<span className="text-emerald-600">Kit</span></Link><nav className="hidden gap-5 text-sm text-slate-500 md:flex"><Link href="/#explorar">Explorar</Link><Link className={active === 'Biblioteca' ? 'font-semibold text-slate-950' : ''} href="/biblioteca">Biblioteca</Link><Link className="text-amber-700" href="/ataques-controlados">Ataques controlados</Link><Link className="text-emerald-700" href="/proponer-comando">Proponer comando</Link><Link href="/casos">Casos de uso</Link><Link href="/laboratorio">Laboratorio</Link><Link href="/seguridad">Seguridad</Link></nav><BookOpen className="size-5 text-emerald-600 md:hidden" /></div></header> }
